using PrayerShutdown.Common.Localization;

namespace PrayerShutdown.Features.PrayerDashboard;

public static class DailyWisdomProvider
{
    public static (string Text, string Source) GetForToday()
    {
        int index = DateTime.Now.DayOfYear % Entries.Length;
        var e = Entries[index];
        return LocalizationService.Instance.CurrentLanguage == "ru"
            ? (e.Ru, e.SrcRu)
            : (e.En, e.SrcEn);
    }

    private static readonly W[] Entries =
    [
        new("The best among you are those who learn the Quran and teach it.",
            "Sahih al-Bukhari",
            "Лучшие из вас те, кто изучает Коран и обучает ему.",
            "Сахих аль-Бухари"),
        new("Whoever believes in Allah and the Last Day, let him speak good or remain silent.",
            "Sahih al-Bukhari & Muslim",
            "Кто верует в Аллаха и Судный день, пусть говорит благое или молчит.",
            "Сахих аль-Бухари и Муслим"),
        new("None of you truly believes until he loves for his brother what he loves for himself.",
            "Sahih al-Bukhari & Muslim",
            "Не уверует никто из вас, пока не полюбит для брата своего то, что любит для себя.",
            "Сахих аль-Бухари и Муслим"),
        new("The strong person is not the one who wrestles others down. The strong person is the one who controls himself when angry.",
            "Sahih al-Bukhari & Muslim",
            "Сильный — не тот, кто побеждает в борьбе, а тот, кто владеет собой в гневе.",
            "Сахих аль-Бухари и Муслим"),
        new("Make things easy and do not make them difficult. Give good news and do not drive people away.",
            "Sahih al-Bukhari",
            "Облегчайте, а не усложняйте. Радуйте, а не отталкивайте.",
            "Сахих аль-Бухари"),
        new("Whoever treads a path seeking knowledge, Allah will make easy for him the path to Paradise.",
            "Sahih Muslim",
            "Кто встал на путь поиска знаний, тому Аллах облегчит путь в Рай.",
            "Сахих Муслим"),
        new("The best of people are those most beneficial to people.",
            "al-Tabarani",
            "Лучшие из людей — приносящие наибольшую пользу людям.",
            "ат-Табарани"),
        new("A good word is charity.",
            "Sahih al-Bukhari & Muslim",
            "Доброе слово — это милостыня.",
            "Сахих аль-Бухари и Муслим"),
        new("Allah does not look at your appearance or wealth, but rather at your hearts and actions.",
            "Sahih Muslim",
            "Аллах не смотрит на вашу внешность и богатство, а смотрит на ваши сердца и деяния.",
            "Сахих Муслим"),
        new("Take advantage of five before five: your youth before old age, health before sickness, wealth before poverty, free time before busyness, and life before death.",
            "al-Hakim",
            "Пользуйся пятью до пяти: молодостью до старости, здоровьем до болезни, достатком до бедности, свободным временем до занятости и жизнью до смерти.",
            "аль-Хаким"),
        new("The most beloved deeds to Allah are those done consistently, even if small.",
            "Sahih al-Bukhari & Muslim",
            "Самые любимые дела перед Аллахом — совершаемые постоянно, даже если они малы.",
            "Сахих аль-Бухари и Муслим"),
        new("Smiling at your brother is charity.",
            "al-Tirmidhi",
            "Улыбка брату твоему — это милостыня.",
            "ат-Тирмизи"),
        new("He who does not thank people does not thank Allah.",
            "Abu Dawud & al-Tirmidhi",
            "Кто не благодарит людей, тот не благодарит Аллаха.",
            "Абу Дауд и ат-Тирмизи"),
        new("Feed the hungry, visit the sick, and free the captive.",
            "Sahih al-Bukhari",
            "Кормите голодных, навещайте больных и освобождайте пленных.",
            "Сахих аль-Бухари"),
        new("Modesty brings nothing but good.",
            "Sahih al-Bukhari & Muslim",
            "Стыдливость приносит только благо.",
            "Сахих аль-Бухари и Муслим"),
        new("Do not be angry, and Paradise is yours.",
            "al-Tabarani",
            "Не гневайся — и Рай будет твоим.",
            "ат-Табарани"),
        new("Leave that which makes you doubt for that which does not make you doubt.",
            "al-Tirmidhi & al-Nasa'i",
            "Оставь то, что вызывает у тебя сомнения, ради того, что сомнений не вызывает.",
            "ат-Тирмизи и ан-Насаи"),
        new("The best remembrance is 'There is no god but Allah' and the best supplication is 'All praise is due to Allah.'",
            "al-Tirmidhi",
            "Лучшее поминание — «Нет бога, кроме Аллаха», а лучшая мольба — «Хвала Аллаху».",
            "ат-Тирмизи"),
        new("Kindness is not found in anything except that it beautifies it.",
            "Sahih Muslim",
            "Мягкость не присутствует в чём-либо, не украшая его.",
            "Сахих Муслим"),
        new("Whoever is not merciful to others will not be treated mercifully.",
            "Sahih al-Bukhari & Muslim",
            "Кто не проявляет милосердие к людям, к тому не будет проявлено милосердие.",
            "Сахих аль-Бухари и Муслим"),
        new("The believer is not stung from the same hole twice.",
            "Sahih al-Bukhari & Muslim",
            "Верующего не жалят дважды из одной норы.",
            "Сахих аль-Бухари и Муслим"),
        new("Cleanliness is half of faith.",
            "Sahih Muslim",
            "Чистота — половина веры.",
            "Сахих Муслим"),
        new("The best prayer after the obligatory prayers is the night prayer.",
            "Sahih Muslim",
            "Лучшая молитва после обязательных — ночная молитва.",
            "Сахих Муслим"),
        new("Speak the truth even if it is bitter.",
            "Ibn Hibban",
            "Говори правду, даже если она горька.",
            "Ибн Хиббан"),
        new("Verily, with hardship comes ease.",
            "Quran 94:6",
            "Поистине, за трудностью следует облегчение.",
            "Коран 94:6"),
    ];

    private sealed record W(string En, string SrcEn, string Ru, string SrcRu);
}
